version: '3'
services:
  sample-go:
    build: .
    ports:
      - 8000:8080
    volumes:
      - .:/go/src/sample_golang
    command: go run ./sample_golang/run/main.go
    container_name: sample-go
volumes:
  data:
    driver: local